### ISSUE TITLE
Beslutte nytt repo, hvilke segmenter skal kjøre på gammelt system (dokumentere de factobeslutningen)

### ISSUE THREAD

**Issue by hansdragnes** [Informasjonsforvaltning/fokus#7]
Oppsummere og sammenstille pro og contra for etablering av oppusset fdk på ny teknologi, og vår anbefaling og beslutning.
(For å kunne dele med andre om nødvendighet, og for sporbarhet)

**Comment by hegeaal** [comment]
Arkitektur-beslutning ligger her: https://github.com/Informasjonsforvaltning/architecture-decision-log/issues/3
